import SwiftUI
import SwiftData
import MessageUI
import UserNotifications

// MARK: - Report Generator

struct MileageReportGenerator {
    static func generateHTML(records: [MileageRecord], start: Date, end: Date) -> String {
        let totalMiles = records.reduce(0) { $0 + $1.miles }
        let totalReimbursement = records.reduce(0) { $0 + $1.reimbursement }

        let df = DateFormatter(); df.dateStyle = .medium
        let tf = DateFormatter(); tf.timeStyle = .short
        let cf = NumberFormatter(); cf.numberStyle = .currency; cf.currencyCode = "USD"
        func currency(_ v: Double) -> String { cf.string(from: NSNumber(value: v)) ?? "$0.00" }

        var byCompany: [String: (miles: Double, amount: Double)] = [:]
        for r in records {
            let e = byCompany[r.company] ?? (0, 0)
            byCompany[r.company] = (e.miles + r.miles, e.amount + r.reimbursement)
        }

        var html = """
        <!DOCTYPE html><html><head><meta charset="UTF-8">
        <style>
        body{font-family:-apple-system,Arial,sans-serif;color:#333;padding:24px;max-width:840px;margin:0 auto}
        h1{color:#1a73e8;margin-bottom:4px;font-size:26px}
        .period{color:#666;font-size:14px;margin-bottom:20px}
        .summary{background:#f0f7ff;border-radius:10px;padding:18px 24px;margin:16px 0;display:flex;gap:36px;flex-wrap:wrap}
        .stat{display:flex;flex-direction:column;gap:2px}
        .stat .label{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:.5px}
        .stat .value{font-size:22px;font-weight:700;color:#222}
        .stat .value.green{color:#1e7e34}
        h2{color:#555;font-size:14px;text-transform:uppercase;letter-spacing:.5px;margin-top:32px;border-bottom:1px solid #eee;padding-bottom:6px}
        table{width:100%;border-collapse:collapse;font-size:13px;margin-top:6px}
        th{background:#f8f8f8;text-align:left;padding:9px 12px;border-bottom:2px solid #e0e0e0;white-space:nowrap}
        td{padding:8px 12px;border-bottom:1px solid #f0f0f0;vertical-align:top}
        tr:last-child td{border-bottom:none}
        .total-row td{font-weight:700;background:#fafafa;border-top:2px solid #ddd;border-bottom:none}
        .green{color:#1e7e34}
        .footer{font-size:11px;color:#bbb;margin-top:36px;padding-top:12px;border-top:1px solid #eee}
        </style></head><body>
        <h1>Mileage Report</h1>
        <div class="period">\(df.string(from: start)) &ndash; \(df.string(from: end))</div>
        <div class="summary">
          <div class="stat"><span class="label">Total Miles</span><span class="value">\(String(format: "%.1f mi", totalMiles))</span></div>
          <div class="stat"><span class="label">Reimbursement</span><span class="value green">\(currency(totalReimbursement))</span></div>
          <div class="stat"><span class="label">Trips</span><span class="value">\(records.count)</span></div>
        </div>
        """

        if !byCompany.isEmpty {
            html += "<h2>By Company</h2><table><tr><th>Company</th><th>Miles</th><th>Reimbursement</th></tr>"
            for (company, s) in byCompany.sorted(by: { $0.key < $1.key }) {
                html += "<tr><td>\(company)</td><td>\(String(format: "%.1f mi", s.miles))</td><td class='green'>\(currency(s.amount))</td></tr>"
            }
            html += "</table>"
        }

        html += "<h2>Trip Details</h2>"
        if records.isEmpty {
            html += "<p style='color:#999;font-style:italic'>No trips recorded in this period.</p>"
        } else {
            html += "<table><tr><th>Date</th><th>Employee</th><th>Company</th><th>Project</th><th>Start</th><th>End</th><th>Miles</th><th>Rate</th><th>Amount</th></tr>"
            for r in records.sorted(by: { $0.date < $1.date }) {
                html += "<tr>"
                html += "<td>\(df.string(from: r.date))</td>"
                html += "<td>\(r.employeeName.isEmpty ? "—" : r.employeeName)</td>"
                html += "<td>\(r.company)</td>"
                html += "<td>\(r.project)</td>"
                html += "<td>\(tf.string(from: r.startTime))</td>"
                html += "<td>\(r.endTime.map { tf.string(from: $0) } ?? "—")</td>"
                html += "<td>\(String(format: "%.1f mi", r.miles))</td>"
                html += "<td>$\(String(format: "%.3f", r.irsRate))</td>"
                html += "<td class='green'>\(currency(r.reimbursement))</td>"
                html += "</tr>"
            }
            html += "<tr class='total-row'><td colspan='6'>Total</td><td>\(String(format: "%.1f mi", totalMiles))</td><td></td><td class='green'>\(currency(totalReimbursement))</td></tr>"
            html += "</table>"
        }

        html += "<p class='footer'>Generated by Mileage Tracker &nbsp;&bull;&nbsp; \(df.string(from: Date()))</p></body></html>"
        return html
    }
}

// MARK: - Mail Compose (UIKit bridge)

struct MailComposeView: UIViewControllerRepresentable {
    let subject: String
    let htmlBody: String
    let toRecipients: [String]
    var onDismiss: (MFMailComposeResult) -> Void

    func makeUIViewController(context: Context) -> MFMailComposeViewController {
        let vc = MFMailComposeViewController()
        vc.mailComposeDelegate = context.coordinator
        vc.setSubject(subject)
        vc.setToRecipients(toRecipients)
        vc.setMessageBody(htmlBody, isHTML: true)
        return vc
    }

    func updateUIViewController(_ uiViewController: MFMailComposeViewController, context: Context) {}
    func makeCoordinator() -> Coordinator { Coordinator(onDismiss: onDismiss) }

    class Coordinator: NSObject, MFMailComposeViewControllerDelegate {
        let onDismiss: (MFMailComposeResult) -> Void
        init(onDismiss: @escaping (MFMailComposeResult) -> Void) { self.onDismiss = onDismiss }
        func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
            controller.dismiss(animated: true)
            onDismiss(result)
        }
    }
}

// MARK: - Bi-Weekly Reminder

enum BiWeeklyReminderManager {
    private static let id = "mileage.biweekly_report"

    static func requestAndSchedule() {
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound]) { granted, _ in
            if granted { schedule() }
        }
    }

    static func schedule() {
        let content = UNMutableNotificationContent()
        content.title = "Mileage Report Reminder"
        content.body = "Time to send your bi-weekly mileage report."
        content.sound = .default
        let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 14 * 24 * 60 * 60, repeats: true)
        let request = UNNotificationRequest(identifier: id, content: content, trigger: trigger)
        UNUserNotificationCenter.current().removePendingNotificationRequests(withIdentifiers: [id])
        UNUserNotificationCenter.current().add(request)
    }

    static func cancel() {
        UNUserNotificationCenter.current().removePendingNotificationRequests(withIdentifiers: [id])
    }

    static func isScheduled(completion: @escaping (Bool) -> Void) {
        UNUserNotificationCenter.current().getPendingNotificationRequests { requests in
            DispatchQueue.main.async {
                completion(requests.contains { $0.identifier == id })
            }
        }
    }
}

// MARK: - Send Report Sheet

struct SendReportView: View {
    @Environment(\.dismiss) private var dismiss
    @Query(sort: \MileageRecord.date, order: .reverse) private var allRecords: [MileageRecord]

    @State private var startDate = Calendar.current.date(byAdding: .day, value: -14, to: Date())!
    @State private var endDate = Date()
    @State private var showMailCompose = false
    @State private var showNoMailAlert = false
    @State private var reminderEnabled = false
    @State private var showSentConfirmation = false

    private var reportRecords: [MileageRecord] {
        let dayStart = Calendar.current.startOfDay(for: startDate)
        let dayEnd   = Calendar.current.date(byAdding: .day, value: 1,
                           to: Calendar.current.startOfDay(for: endDate))!
        return allRecords.filter { $0.date >= dayStart && $0.date < dayEnd }
    }

    private var totalMiles: Double { reportRecords.reduce(0) { $0 + $1.miles } }
    private var totalReimbursement: Double { reportRecords.reduce(0) { $0 + $1.reimbursement } }

    private var reportSubject: String {
        let df = DateFormatter(); df.dateStyle = .medium
        return "Mileage Report: \(df.string(from: startDate)) – \(df.string(from: endDate))"
    }

    var body: some View {
        NavigationStack {
            Form {
                Section {
                    DatePicker("Start Date", selection: $startDate, displayedComponents: .date)
                    DatePicker("End Date", selection: $endDate, in: startDate..., displayedComponents: .date)
                    Button("Reset to Last 14 Days") {
                        endDate = Date()
                        startDate = Calendar.current.date(byAdding: .day, value: -14, to: endDate)!
                    }
                    .font(.subheadline)
                } header: { Text("Report Period") }

                Section {
                    LabeledContent("Trips", value: "\(reportRecords.count)")
                    LabeledContent("Total Miles", value: String(format: "%.1f mi", totalMiles))
                    LabeledContent("Est. Reimbursement") {
                        Text(totalReimbursement, format: .currency(code: "USD")).foregroundStyle(.green)
                    }
                } header: { Text("Preview") }

                Section {
                    Button {
                        if MFMailComposeViewController.canSendMail() {
                            showMailCompose = true
                        } else {
                            showNoMailAlert = true
                        }
                    } label: {
                        Label("Send via Email", systemImage: "envelope.fill")
                    }
                } footer: {
                    Text("Opens the iOS Mail app with a formatted HTML report pre-filled. You can edit recipients before sending.")
                }

                Section {
                    Toggle("Bi-Weekly Reminder", isOn: $reminderEnabled)
                        .onChange(of: reminderEnabled) { _, enabled in
                            enabled ? BiWeeklyReminderManager.requestAndSchedule()
                                    : BiWeeklyReminderManager.cancel()
                        }
                } header: {
                    Text("Reminders")
                } footer: {
                    Text("A notification will appear every 14 days reminding you to send your mileage report.")
                }
            }
            .navigationTitle("Email Report")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") { dismiss() }
                }
            }
            .sheet(isPresented: $showMailCompose) {
                MailComposeView(
                    subject: reportSubject,
                    htmlBody: MileageReportGenerator.generateHTML(
                        records: reportRecords,
                        start: startDate,
                        end: endDate
                    ),
                    toRecipients: []
                ) { result in
                    if result == .sent { showSentConfirmation = true }
                }
            }
            .alert("Mail Not Available", isPresented: $showNoMailAlert) {
                Button("OK") {}
            } message: {
                Text("No mail account is configured on this device. Go to Settings → Mail → Accounts to add one, then try again.")
            }
            .alert("Report Sent", isPresented: $showSentConfirmation) {
                Button("OK") { dismiss() }
            } message: {
                Text("Your mileage report has been sent.")
            }
        }
        .onAppear {
            BiWeeklyReminderManager.isScheduled { reminderEnabled = $0 }
        }
    }
}
